name: Project CI
on: push
env:
  docker_username: ${{ secrets.DOCKER_USERNAME }}
  docker_password: ${{ secrets.DOCKER_PASSWORD }}
  GIT_COMMIT: ${{ github.sha }}

jobs:
  cloneDown:
    runs-on: ubuntu-latest
    steps:
      - name: Clone-down
        uses: actions/checkout@v2

      - name: Upload-repo
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: .

  Build backend:
    runs-on: ubuntu-latest
    needs: cloneDown
    steps:
      - name: Download-repo
        uses: actions/download-artifact@v2
        with:
          name: code
          path: .

      - name: backend-run
        working-directory: ./backend
        run: go run backend

  Build frontend:
    runs-on: ubuntu-latest
    needs: cloneDown
    steps:
      - name: Download-repo
        uses: actions/download-artifact@v2
        with:
          name: code
          path: .

      - name: frontend-run
        working-directory: ./frontend
        run: go run frontend

  test:
    runs-on: ubuntu-latest
    needs: cloneDown
    steps:
      - name: Download-repo
        uses: actions/download-artifact@v2
        with:
          name: code
          path: .

      - name: test
        working-directory: ./frontend
        run: go test

  Docker backend :
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Download-repo
        uses: actions/download-artifact@v2
        with:
          name: code
          path: .

      - name: build-docker-backend
        working-directory: ./backend
        run: chmod +x ci/build-docker-backend.sh && ci/build-docker-backend.sh

      - name: build-docker-frontend
        working-directory: ./frontend
        run: chmod +x ci/build-docker-frontend.sh && ci/build-docker-frontend.sh
      
      - name: push-docker-frontend
        run: chmod +x ci/push-docker.sh && ci/push-docker.sh

      - name: push-docker-backend
        run: chmod +x ci/push-docker.sh && ci/push-docker.sh        


    
